mysite/landing/urls.py
from django.urls import path, include
from . import views

app_name = "landing"

urlpatterns = [
	path('', views.home, name = 'landing-home'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('upload/', include('upload.urls', namespace='upload')),
    path('', include('landing.urls', namespace='landing')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/upload/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "upload"

urlpatterns = [
	path('selection/', views.upload_file, name="upload-selection"),
	path('filelist/', views.list_files, name="upload-filelist"),
]

mysite/users/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = "users"

urlpatterns = [
	path('register', views.register, name='users-registration'),
	path('login', auth_views.LoginView.as_view(template_name='users/login.html'), name='users-login'),
	path('logout', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='users-logout'),
]

mysite/upload/models.py
from django.db import models
from users.models import Profile
from django.contrib.auth.models import User

class Upload(models.Model):
	file_name = models.FileField(upload_to='pdfs')
	uploaded_at = models.DateTimeField(auto_now_add=True)
	activated = models.BooleanField(default=False)
	text = models.TextField(null=True)
	user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

	def __str__(self):
		return f"File id: {self.id}"



'''
Example of a model for uploading documents

class Upload(models.Model):
	title = models.CharField(max_length=100)
	author = models.CharField(max_length=100)
	pdf = models.FileField(upload_to='books/pdfs/')

	def __str__(self):
		return self.title
'''

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
	user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)

	def __str__(self):
		return f'{self.user.username} Profile'

mysite/landing/forms.py
from django.forms import ModelForm
from .models import PDFModel

class UploadForm(ModelForm):
	class Meta:
		model = PDFModel
		fields = ('title', 'pdf')

mysite/upload/forms.py
from django import forms

from .models import Upload

class UploadForm(forms.ModelForm):
	class Meta:
		model = Upload
		fields = ('file_name',)

mysite/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
	# required defaults to true
	email = forms.EmailField()

	class Meta:
		# telling the form which model it's interacting with
		model = User
		# telling the form which fields the form is going to display, in order
		fields = ['username', 'email', 'password1', 'password2']

mysite/landing/views.py
from django.shortcuts import render


# Create your views here.
def home(request):
	current_user = request.user
	if current_user is None:
		current_user = "Login Please"

	return render(request, 'landing/landing.html', {'user' : current_user})

mysite/upload/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required

from .forms import UploadForm
from .models import Upload

import pdfplumber

def extract_pdf(file):
	text = ""

	with pdfplumber.open(file) as pdf:
		print(pdf.metadata)
		for page in pdf.pages:
			extracted_text = page.extract_text()
			cleaned_text = ' '.join(extracted_text.split())
			text += cleaned_text
			page.close()
	pdf.close()

	return text

@login_required(login_url='users:users-login')
def upload_file(request):
	if request.method == 'POST':
		form = UploadForm(request.POST, request.FILES)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.user = request.user
			filepath = obj.file_name
			obj.text = extract_pdf(filepath)
			obj.save()

			return redirect('upload:upload-filelist')

	else:
		form = UploadForm()

	return render(request, 'upload/upload_file.html', {"form" : form})

@login_required(login_url='users:users-login')
def list_files(request):
	current_user = request.user
	uploads = Upload.objects.filter(user=current_user)
	return render(request, 'upload/list_file.html', {'uploads' : uploads})

mysite/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserRegisterForm

'''
Register View
	- handles if the user is trying to view the page initially(GET) or if they are trying to submit
	  information (POST)
	- 
'''
def register(request):
	if request.method == 'POST':
		form = UserRegisterForm(request.POST)
		if form.is_valid():
			form.save()

			# This part here is how you access data from the form
			username = form.cleaned_data.get('username')

			# Outputting a success message
			messages.success(request, f"Account created for {username}")

			#Redirecting the user to the login page once account is created
			return redirect('landing:landing-home')

	# When the user is loading the page/form
	else:
		# Creating a blank form, vs in the POST version we load the data the user entered
		form = UserRegisterForm()

	return render(request, 'users/register.html', {'form' : form})

mysite/landing/templates/landing/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>

	<!-- Nav Bar -->
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
	  <a class="navbar-brand" href="{% url 'landing:landing-home' %}">Papertrail</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item active">
	        <a class="nav-link" href="{% url 'upload:upload-selection' %}">Upload<span class="sr-only">(current)</span></a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="{% url 'upload:upload-filelist' %}">View Uploads</a>
	      </li>
	      <li class="nav-item dropdown">
	        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          Account
	        </a>
	        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
	          <a class="dropdown-item" href="#">Profile</a>
	          <div class="dropdown-divider"></div>
	          <a class="dropdown-item" href="{% url 'users:users-registration' %}">Register</a>
	          <a class="dropdown-item" href="{% url 'users:users-login' %}">Login</a>
	          <a class="dropdown-item" href="{% url 'users:users-logout' %}">Logout</a>
	        </div>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link disabled" href="#">Logged In As {{user}}</a>
	      </li>
	    </ul>
	  </div>
	</nav>
	<!-- End of Nav Bar -->


	{% block content %}

	{% endblock content %}


	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

mysite/landing/templates/landing/landing.html
{% extends "landing/base.html" %}

{% block content %}
<h2>landing page</h2>
{% endblock content %}

mysite/upload/templates/upload/list_file.html
{% extends "landing/base.html" %}

{% block content %}
	<h2>Uploaded Files</h2>

	<table class="table">
		<thead>
			<tr>
				<th>Id</th>
				<th>Path</th>
				<th>User</th>
				<th>Text</th>
			</tr>
		</thead>
		<tbody>
			{% for upload in uploads %}
				<tr>
					<td>{{ upload.id }}</td>
					<td>{{ upload.file_name }}</td>
					<td>{{ upload.user }}</td>
					<td>{{ upload.text }}</td>
				</tr>
			{% endfor %}
	</table>
{% endblock content %}

mysite/upload/templates/upload/upload_file.html
{% extends 'landing/base.html' %}

{% block content %}
	<h2>Upload File</h2>
	<form method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="btn btn-primary">Upload File</button>
	</form>
{% endblock content %}

mysite/users/templates/users/login.html
{% extends "landing/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group"> 
				<legend class="border-bottom mb-4">Log In</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Log In</button>
			</div>
		</form>
		<div class="border-top pt-3">
			<small class="text-muted">
				Need an account?
				<a class="ml-2" href="{% url 'users:users-registration' %}">Sign Up</a>
			</small>
		</div>
	</div>
{% endblock content %}

mysite/users/templates/users/logout.html
{% extends "landing/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
	<h2>You Have Been Logged Out</h2>	
	<div class="border-top pt-3">
		<small class="text-muted">
			<a class="ml-2" href="{% url 'login'}">Login</a>
		</small>
	</div>
{% endblock content %}

mysite/users/templates/users/register.html
{% extends "landing/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group"> 
				<legend class="border-bottom mb-4">Join Today</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Sign Up</button>
			</div>
		</form>
		<div class="border-top pt-3">
			<small class="text-muted">
				Already have an account?
				<a class="ml-2" href="#">Sign In</a>
			</small>
		</div>
	</div>
{% endblock content %}